title: "HomeRange"
description: "This repository contains the latest version of the HomeRange data and R package."

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-cayman
